import ProjectDescription

let workspace = Workspace(
    name: "LynxWebGPUDemo",
    projects: [
        "Projects/WebGPUDemo",
        // Dawn 백엔드 검증 — 같은 워크스페이스의 별도 프로젝트다. 스킴: DawnCheck(적합성 테스트) ·
        // DawnDemo(화면 실증 앱). 데모 로직과는 완전히 분리되어 있고, 여기 있어야
        // `tuist generate` 한 번으로 세 스킴이 다 보인다.
        "Projects/DawnCheck",
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
