import ProjectDescription

let workspace = Workspace(
    name: "LynxWebGPUDemo",
    projects: [
        "Projects/WebGPUDemo",
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
