import ProjectDescription

let workspace = Workspace(
    name: "LynxWebGPUDemo",
    projects: [
        "Projects/WebGPUDemo",
        // Dawn backend verification — a separate project in the same workspace. Schemes: DawnCheck
        // (conformance tests) and DawnDemo (an on-screen demonstration app). It is fully separated from
        // the demo logic, and belongs here so one `tuist generate` surfaces every scheme.
        "Projects/DawnCheck",
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
